name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Set environment variables
        uses: ./.github/actions/dotenv-action
        with:
          env_file: .env

      - name: Install dependencies
        run: flutter pub get
        env:
          API_KEY: ${{ secrets.API_KEY }}
